// scripts/lib/playwright-secrets.mjs — one Playwright MCP `--secrets` file for every env.
//
// A Playwright MCP server reads its `--secrets` dotenv once, at start, and substitutes a value only when
// the typed text equals a key NAME in it. With one file per env, a server types one env's passwords for
// its whole life, so changing env means restarting every lane. The combined file holds every env's
// passwords under the `KEY_<ENV>` names resolveTestEnv() already gives `.env.playwright.<env>`
// (ORG_USER_PASSWORD in `.env.playwright.vcst_qa` → ORG_USER_PASSWORD_VCST_QA), so one server serves
// every env and the env travels in the typed name.
//
// The per-env files stay the source of truth (the scripts read them too); this file is derived from them.
// Each `KEY=<raw value>` line is copied with only its key renamed, so a value parses exactly as it does
// in its own file, and the result is parsed back and compared with the sources before it is returned.
// Used by `npm run secrets:playwright` (scripts/auth/build-playwright-secrets.mjs) and by
// .claude/hooks/enforce-secret-token.mjs.

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'dotenv';
import { envSuffix, TEST_ENV_PATTERN } from './resolve-test-env.js';

export const COMBINED_SECRETS_FILE = '.env.playwright.all';
/** First line of every generated file: how a reader tells the combined file from a single-env one. */
export const COMBINED_SECRETS_MARK = `# ${COMBINED_SECRETS_FILE} — generated by \`npm run secrets:playwright\`; do not edit.`;
const ENVS_LINE = /^# envs: (.*)$/m;
const ENTRY = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/;
/** `.env.playwright.<name>` files that are not an env: the generic single-env file and the combined file itself. */
const NOT_ENVS = new Set(['local', 'all']);

/** `KEY=<raw value>` entries of a dotenv text, values exactly as written. A repeated key keeps its last value, as dotenv does. */
export function rawEntries(text) {
  const out = new Map();
  for (const line of text.split(/\r?\n/)) {
    const m = ENTRY.exec(line);
    if (m && !line.trimStart().startsWith('#')) out.set(m[1], m[2]);
  }
  return out;
}

/** The env list of a combined file, or null when the text is not one (a single-env file with bare keys). */
export function combinedEnvs(text) {
  if (!text.startsWith(COMBINED_SECRETS_MARK)) return null;
  return (ENVS_LINE.exec(text)?.[1] ?? '').split(/\s+/).filter(Boolean);
}

/** `{ env, key }` of an env-qualified name, by the longest suffix among `envs`; null when none matches. */
export function splitQualifiedName(name, envs) {
  for (const env of [...envs].sort((a, b) => b.length - a.length)) {
    const suffix = envSuffix(env);
    if (name.length > suffix.length && name.endsWith(suffix)) return { env, key: name.slice(0, -suffix.length) };
  }
  return null;
}

/** True when any env file marks the env production (`ENV_RISK`, or its `ENV_RISK_<ENV>` pin). Stricter than
 *  config.js's layering on purpose: a `.env.local` ENV_RISK=dev must not slip a production env into every lane. */
function markedProduction(root, env) {
  return ['.env.defaults', `.env.${env}`, '.env.local'].map((f) => join(root, f)).filter(existsSync)
    .map((p) => parse(readFileSync(p)))
    .some((vars) => [vars.ENV_RISK, vars[`ENV_RISK${envSuffix(env)}`]].some((v) => v?.trim().toLowerCase() === 'production'));
}

/**
 * Build the combined file from every `.env.playwright.<env>` under `root` whose env has its own `.env.<env>`.
 * Production-risk envs stay out: every lane loads this file. Empty values are skipped, because Playwright
 * treats an empty secret as a miss and would redact the empty string all through its output.
 * Returns `{ text, envs: [{ env, keys, empty }], excluded: [{ env, reason }], entries }`, where `entries`
 * maps each written name to `{ env, key, raw }`. Throws when two envs would write one name, or when the
 * text does not parse back to its sources. Never puts a value in an error message.
 */
export function buildCombinedSecrets(root) {
  const envs = [], excluded = [], blocks = [], entries = new Map(), sources = new Map();
  const names = readdirSync(root).map((f) => /^\.env\.playwright\.(.+)$/.exec(f)?.[1]).filter(Boolean).sort();
  for (const env of names) {
    const file = `.env.playwright.${env}`;
    const text = readFileSync(join(root, file), 'utf8');
    const parsed = parse(text);
    const nonEmpty = Object.keys(parsed).filter((k) => parsed[k]);
    if (NOT_ENVS.has(env)) {
      if (env === 'local' && nonEmpty.length) excluded.push({ env, reason: `${file} names no env (its keys stay bare)` });
      continue;
    }
    const reason = !TEST_ENV_PATTERN.test(env) ? 'not a TEST_ENV name ([a-z0-9_]+)'
      : !existsSync(join(root, `.env.${env}`)) ? `no .env.${env}`
      : markedProduction(root, env) ? 'ENV_RISK=production'
      : !nonEmpty.length ? 'no non-empty keys' : null;
    if (reason) { excluded.push({ env, reason }); continue; }

    const raw = rawEntries(text);
    const missed = nonEmpty.filter((k) => !raw.has(k));
    if (missed.length) throw new Error(`${file}: ${missed.join(', ')} not on a single KEY=value line; keep each password on one line`);
    const lines = [], empty = [];
    for (const [key, value] of raw) {
      if (!parsed[key]) { empty.push(key); continue; }
      const name = key + envSuffix(env);
      const clash = entries.get(name);
      if (clash) throw new Error(`${name} would come from both ${clash.env} (${clash.key}) and ${env} (${key}); rename one of the keys`);
      entries.set(name, { env, key, raw: value });
      lines.push(`${name}=${value}`);
    }
    sources.set(env, parsed);
    envs.push({ env, keys: lines.length, empty });
    blocks.push(`# --- ${env} (${file}) ---\n${lines.join('\n')}`);
  }

  const text = [
    COMBINED_SECRETS_MARK,
    '# Every env\'s Playwright login passwords as KEY_<ENV>: type ORG_USER_PASSWORD_VCST_QA to sign in on vcst_qa.',
    '# Edit .env.playwright.<env>, re-run, then restart the Playwright MCP servers: they read this file once, at start.',
    `# envs: ${envs.map((e) => e.env).join(' ')}`,
    '',
    blocks.join('\n\n'),
    '',
  ].join('\n');

  const back = parse(text);
  const wrong = [...entries].filter(([name, { env, key }]) => back[name] !== sources.get(env)[key]).map(([name]) => name);
  if (wrong.length || Object.keys(back).length !== entries.size) {
    throw new Error(`the combined file would not parse back to its sources${wrong.length ? `: ${wrong.join(', ')}` : ''}`);
  }
  return { text, envs, excluded, entries };
}
